### ISSUE TITLE
argument of type 'Http' is not assignable to parameter of type 'HttpClient' using @ngx-universal/translate-loader 

### ISSUE THREAD

**Issue by ilDon** [ngx-universal/translate-loader#32]
**I'm submitting a**
```
[ ] Regression
[ ] Bug report 
[ ] Support request
[ ] Feature request
[X] Documentation issue or request
```

**Current behavior**
I'm following the instruction in the npm repository page to use [@ngx-universal/translate-loader](https://www.npmjs.com/package/@ngx-universal/translate-loader), but I've encountered some issues with the example.

First, it would be useful to clarify that we need to import `PLATFORM_ID` and `Inject` like so:

    import { NgModule, Inject, PLATFORM_ID } from '@angular/core';

Second, there is an error in the example. Currently it states this:
```
export function translateFactory(platformId: any, http: Http): TranslateLoader {
  const browserLoader = new TranslateHttpLoader(http);
  return new UniversalTranslateLoader(platformId, browserLoader, './public/assets/i18n');
}
```
But this throws this error: `app.module.ts (29,49): Argument of type 'Http' is not assignable to parameter of type 'HttpClient'`

Third, when fixing that error (with the code provided below), a new error is thrown: `Module not found: Error: Can't resolve '@ngx-cache/core'` 

**Expected/desired behavior**

The example should have this code:
```
...
import { HttpClient } from '@angular/common/http';
...
export function translateFactory(platformId: any, http: Http, httpClient: HttpClient): TranslateLoader {
  const browserLoader = new TranslateHttpLoader(httpClient);
  return new UniversalTranslateLoader(platformId, browserLoader, './i18n');
}
...
TranslateModule.forRoot({
    loader: {
      provide: TranslateLoader,
      useFactory: (translateFactory),
      deps: [PLATFORM_ID, Http, HttpClient]
    }
  }),
```

And it should be mentioned that `@ngx-universal/translate-loader` depends on `'@ngx-cache/core'`. Or this package should be added to the dependencies of `@ngx-universal/translate-loader`.

**Minimal reproduction of the problem with instructions**
Build a new app with angular-cli (`ng new apptest`);
Add `ngx-translate`.
Follow the steps to make the app universal (e.g. [like this](https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal)))
Add `@ngx-universal/translate-loader`.
Use the code from the example.

**Environment**
* angular-devkit/build-optimizer v. 0.0.21
* angular-devkit/core v. 0.0.14
* angular-devkit/schematics v. 0.0.24
* angular/animations v. 4.4.4
* angular/cli v. 1.4.3
* angular/common v. 4.4.3
* angular/compiler-cli v. 4.4.3
* angular/compiler v. 4.4.3
* angular/core v. 4.4.3
* angular/forms v. 4.4.3
* angular/http v. 4.4.3
* angular/language-service v. 4.4.3
* angular/platform-browser-dynamic v. 4.4.3
* angular/platform-browser v. 4.4.3
* angular/platform-server v. 4.4.4
* angular/router v. 4.4.3
* angular/tsc-wrapped v. 4.4.3
* ngtools/json-schema v. 1.1.0
* ngtools/webpack v. 1.7.1
* ngx-translate/core v. 8.0.0
* ngx-translate/http-loader v. 2.0.0
* ngx-universal/translate-loader v. 4.0.1
* webpack-concat-plugin v. 1.4.0
* webpack-dev-middleware v. 1.12.0
* webpack-dev-server v. 2.7.1
* webpack-merge v. 4.1.0
* webpack-sources v. 1.0.1
* webpack v. 3.5.6

* **Browser:**
Not relevant, build issue.

* **For Tooling issues:**
- Node version: 8.6.0
- ts-node v3.3.0
- typescript v2.5.3
- Platform:  Mac, 10.12.6

* Others:
package manager: yarn
HTTP server: express v. 4.15.5

**Comment by fulls1z3** [comment]
now done
